version: "3.3"

services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - 6379
    networks:
      - redis-net
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    networks:
      - redis-net
    environment:
      EULA: "TRUE"
      TYPE: "SPIGOT"
      VERSION: "1.20"
      OVERRIDE_SERVER_PROPERTIES: "FALSE"
      COPY_CONFIG_DEST: "/data/"
      SPIGET_RESOURCES: "19254,28140,46229,18494,6245,96577,111084"
      # 19254: ViaVersion
      # 28140: Luckperms
      # 46229: TabList
      # 18494: DiscordSRV
      # 6245: Placeholder api
      # 96577: Player Time Limit
      # 111084: Ghost anti cheat

    volumes:
      - ./plugins:/plugins
      - ./configs:/config
      - ./data:/data

networks:
  redis-net:
    driver: bridge
