version: "3.3"

services:
  redis:
    image: redis:alpine
    command: redis-server
    ports:
      - "6300:6379"
    networks:
      - redis-net
    environment:
      ALLOW_EMPTY_PASSWORD: "TRUE"
      TZ: "Europe/Berlin"
    restart: always
  discord-bot:
    build: ./discord-bot
    networks:
      - redis-net
    depends_on:
      - redis
      - minecraft
    restart: always
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    depends_on:
      - redis
    ports:
      - "25565:25565"
      - "24454:24454/udp"
      - "25566:25566"
    networks:
      - redis-net
    environment:
      EULA: "TRUE"
      TYPE: "PURPUR"
      VERSION: "1.20.1"
      OVERRIDE_SERVER_PROPERTIES: "FALSE"
      COPY_CONFIG_DEST: "/data/"
      REPLACE_ENV_IN_PLACE: "TRUE"
      REPLACE_ENV_DURING_SYNC: "TRUE"
      INIT_MEMORY: "${min_memory}"
      MAX_MEMORY: "${max_memory}"
      USE_AIKAR_FLAGS: "TRUE"
      JVM_OPTS: "--add-modules=jdk.incubator.vector"
      TZ: "Europe/Berlin"
      # 19254: ViaVersion‚
      # 28140: Luckperms
      # 46229: TabList
      # 18494: DiscordSRV
      # 6245: Placeholder api
      # 96577: Player Time Limit
      # 111084: Ghost anti cheat
      # im ordner: ChatEx
    env_file:
      - minecraft.env

    volumes:
      - ./plugins:/plugins
      - ./configs:/config
      - ./data:/data
    restart: always

networks:
  redis-net:
    driver: bridge
